### ISSUE TITLE
wouldnt changing the diskdrive in registry completely destroy your pc?

### ISSUE THREAD

**Issue by notaps** [anarchysmo/HWIDSpoofer#1]
might seem dumb but spoofers have to do all this bs to prevent bsod / windows destruction, so you'd think just writing to the disk with 0 context or helpers would bsod every time?

**Comment by iparamsh** [comment]
it worked fine for me

**Comment by notaps** [comment]
k

**Comment by smuggood** [comment]
will this work on winver 20H2

**Comment by iparamsh** [comment]
> will this work on winver 20H2

yes
