### ISSUE TITLE
Doesn't change in CMD

### ISSUE THREAD

**Issue by billiedark** [anarchysmo/HWIDSpoofer#5]
![image](https://user-images.githubusercontent.com/60980006/147399160-afbae293-1eb5-407d-84bc-16b936a1cbc7.png)
What should we do in that case, sensei?

**Comment by iparamsh** [comment]
Well, it's changing volume id not serial number, but if you want you can help me with doing so

**Comment by zepc007** [comment]
So what are diffrences between volume id and SN?
